name: history_log_repository
description: Repository accessing for log
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  database_client:
    path: ../database_client
  equatable: ^2.0.3
  rxdart: ^0.27.4

dev_dependencies:
  test: ^1.19.2
