name: database_client
description: Package connecting to the local database
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  drift: ^2.7.0
  drift_dev: any
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^1.11.0
  http: ^0.13.6
  path_provider: ^2.0.14
  flutter:
    sdk: flutter

dev_dependencies:
  build_web_compilers: ^3.2.2
  build_runner: ^2.1.8
  test: ^1.19.2
  build: ^2.3.1
