name: database_client
description: Package connecting to the local database
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.5
  sqlite3: ^1.11.0

dev_dependencies:
  build_runner: ^2.1.11
  drift_dev: any
  test: ^1.19.2
